name: Run Drought Index Workflow
run-name: ${{ github.actor }} is running snakemake workflow 🚀
on: #[push]
  schedule:
    - cron: '0 0 * * *'
jobs:
  Run-Drought-Index-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls
      - name: Get working directory
        run: |
          pwd
      - name: snakemake workflow
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
      - name: configure git on runner
        run: |
          git config --local user.email "sesben@hotmail.com"
          git config --local user.name "esbenlykke"
      - name: commit changes to repository
        run: |
          git add visuals/heatmap_world_drought.png index.html
          git commit -m "new day's rendering"
          git push origin main
      - run: echo "🍏 This job's status is ${{ job.status }}."
